# Generated by Django 5.2.1 on 2025-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='changes_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
