# Generated by Django 5.2.1 on 2025-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_changes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='changes_description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='final_description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
