# Generated by Django 5.2.1 on 2025-06-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_changes_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
