# Generated by Django 5.2.1 on 2025-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_comment_content_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
